---@type LazySpec
return {
	"NeogitOrg/neogit",
	lazy = true,
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
	},
	cmd = "Neogit",
	keys = {
		{ "<leader>gg", "<cmd>Neogit<cr>", desc = "Neogit Status" },
		{ "<leader>gc", "<cmd>Neogit commit<cr>", desc = "Neogit Commit" },
		{ "<leader>gp", "<cmd>Neogit push<cr>", desc = "Neogit Push" },
		{ "<leader>gl", "<cmd>Neogit pull<cr>", desc = "Neogit Pull" },
		{ "<leader>gb", "<cmd>Neogit branch<cr>", desc = "Neogit Branch" },
	},
	opts = {
		disable_hint = false,
		disable_context_highlighting = false,
		disable_signs = false,
		disable_insert_on_commit = "auto",
		filewatcher = {
			interval = 1000,
			enabled = true,
		},
		graph_style = "ascii",
		git_services = {
			["github.com"] = {
				pull_request = "https://github.com/${owner}/${repository}/compare/${branch_name}?expand=1",
				commit = "https://github.com/${owner}/${repository}/commit/${commit}",
				tree = "https://github.com/${owner}/${repository}/tree/${branch_name}",
			},
			["bitbucket.org"] = {
				pull_request = "https://bitbucket.org/${owner}/${repository}/pull-requests/new?source=${branch_name}&t=1",
				commit = "https://bitbucket.org/${owner}/${repository}/commits/${commit}",
				tree = "https://bitbucket.org/${owner}/${repository}/src/${branch_name}",
			},
			["gitlab.com"] = {
				pull_request = "https://gitlab.com/${owner}/${repository}/merge_requests/new?merge_request[source_branch]=${branch_name}",
				commit = "https://gitlab.com/${owner}/${repository}/-/commit/${commit}",
				tree = "https://gitlab.com/${owner}/${repository}/-/tree/${branch_name}",
			},
			["azure.com"] = {
				pull_request = "https://dev.azure.com/${owner}/_git/${repository}/pullrequestcreate?sourceRef=${branch_name}&targetRef=${target}",
				commit = "https://dev.azure.com/${owner}/_git/${repository}/commit/${commit}",
				tree = "https://dev.azure.com/${owner}/_git/${repository}?version=GB${branch_name}",
			},
		},
		remember_settings = true,
		use_per_project_settings = true,
		ignored_settings = {
			"NeogitPushPopup--hierarchical",
			"NeogitPushPopup--hierarchicalIsDefault",
			"NeogitPullPopup--hierarchical",
			"NeogitPullPopup--hierarchicalIsDefault",
			"NeogitCommitPopup--hierarchical",
			"NeogitCommitPopup--hierarchicalIsDefault",
			"NeogitRebasePopup--hierarchical",
			"NeogitRebasePopup--hierarchicalIsDefault",
		},
		auto_refresh = true,
		sort_branches = "-committerdate",
		kind = "tab",
		disable_line_numbers = true,
		console_timeout = 2000,
		auto_show_console = true,
		auto_close_console = true,
		notification_icon = "",
		status = {
			show_head_commit_hash = true,
			recent_commit_count = 10,
			HEAD_padding = 10,
			HEAD_folded = false,
			mode_padding = 3,
			mode_text = {
				M = "modified",
				N = "new file",
				A = "added",
				D = "deleted",
				C = "copied",
				U = "updated",
				R = "renamed",
				DD = "unmerged",
				AU = "unmerged",
				UD = "unmerged",
				UA = "unmerged",
				DU = "unmerged",
				AA = "unmerged",
				UU = "unmerged",
				["?"] = "",
			},
		},
		commit_editor = {
			kind = "tab",
			show_staged_diff = true,
			staged_diff_split_kind = "auto",
			spell_check = true,
		},
		commit_select_view = {
			kind = "tab",
		},
		commit_view = {
			kind = "vsplit",
			verify_commit = vim.fn.executable("gpg") == 1,
		},
		log_view = {
			kind = "tab",
		},
		rebase_editor = {
			kind = "auto",
		},
		reflog_view = {
			kind = "tab",
		},
		merge_editor = {
			kind = "auto",
		},
		description_editor = {
			kind = "auto",
		},
		tag_editor = {
			kind = "auto",
		},
		preview_buffer = {
			kind = "floating_console",
		},
		popup = {
			kind = "split",
		},
		signs = {
			hunk = { "", "" },
			item = { "", "" },
			section = { "", "" },
		},
		integrations = {
			telescope = nil,
			diffview = false,
			fzf_lua = nil,
			mini_pick = nil,
		},
		sections = {
			sequencer = {
				folded = false,
				hidden = false,
			},
			untracked = {
				folded = false,
				hidden = false,
			},
			unstaged = {
				folded = false,
				hidden = false,
			},
			staged = {
				folded = false,
				hidden = false,
			},
			stashes = {
				folded = true,
				hidden = false,
			},
			unpulled_upstream = {
				folded = true,
				hidden = false,
			},
			unmerged_upstream = {
				folded = false,
				hidden = false,
			},
			unpulled_pushRemote = {
				folded = true,
				hidden = false,
			},
			unmerged_pushRemote = {
				folded = false,
				hidden = false,
			},
			recent = {
				folded = true,
				hidden = false,
			},
			rebase = {
				folded = true,
				hidden = false,
			},
		},
		mappings = {
			commit_editor = {
				["q"] = "Close",
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
				["<m-p>"] = "PrevMessage",
				["<m-n>"] = "NextMessage",
				["<m-r>"] = "ResetMessage",
			},
			commit_editor_I = {
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
			},
			rebase_editor = {
				["p"] = "Pick",
				["r"] = "Reword",
				["e"] = "Edit",
				["s"] = "Squash",
				["f"] = "Fixup",
				["x"] = "Execute",
				["d"] = "Drop",
				["b"] = "Break",
				["q"] = "Close",
				["<cr>"] = "OpenCommit",
				["gk"] = "MoveUp",
				["gj"] = "MoveDown",
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
				["[c"] = "OpenOrScrollUp",
				["]c"] = "OpenOrScrollDown",
			},
			rebase_editor_I = {
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
			},
			finder = {
				["<cr>"] = "Select",
				["<c-c>"] = "Close",
				["<esc>"] = "Close",
				["<c-n>"] = "Next",
				["<c-p>"] = "Previous",
				["<down>"] = "Next",
				["<up>"] = "Previous",
				["<tab>"] = "InsertCompletion",
				["<space>"] = "MultiselectToggleNext",
				["<s-space>"] = "MultiselectTogglePrevious",
				["<c-j>"] = "NOP",
				["<ScrollWheelDown>"] = "ScrollWheelDown",
				["<ScrollWheelUp>"] = "ScrollWheelUp",
				["<ScrollWheelLeft>"] = "NOP",
				["<ScrollWheelRight>"] = "NOP",
				["<LeftMouse>"] = "MouseClick",
				["<2-LeftMouse>"] = "NOP",
			},
			popup = {
				["?"] = "HelpPopup",
				["A"] = "CherryPickPopup",
				["D"] = "DiffPopup",
				["M"] = "RemotePopup",
				["P"] = "PushPopup",
				["X"] = "ResetPopup",
				["Z"] = "StashPopup",
				["b"] = "BranchPopup",
				["B"] = "BisectPopup",
				["c"] = "CommitPopup",
				["f"] = "FetchPopup",
				["l"] = "LogPopup",
				["m"] = "MergePopup",
				["p"] = "PullPopup",
				["r"] = "RebasePopup",
				["v"] = "RevertPopup",
				["w"] = "WorktreePopup",
			},
			status = {
				["k"] = "MoveUp",
				["j"] = "MoveDown",
				["q"] = "Close",
				["o"] = "OpenTree",
				["I"] = "InitRepo",
				["1"] = "Depth1",
				["2"] = "Depth2",
				["3"] = "Depth3",
				["4"] = "Depth4",
				["<tab>"] = "Toggle",
				["x"] = "Discard",
				["s"] = "Stage",
				["S"] = "StageUnstaged",
				["<c-s>"] = "StageAll",
				["K"] = "Untrack",
				["u"] = "Unstage",
				["U"] = "UnstageStaged",
				["$"] = "CommandHistory",
				["Y"] = "YankSelected",
				["<c-r>"] = "RefreshBuffer",
				["<cr>"] = "GoToFile",
				["<c-v>"] = "VSplitOpen",
				["<c-x>"] = "SplitOpen",
				["<c-t>"] = "TabOpen",
				["{"] = "GoToPreviousHunkHeader",
				["}"] = "GoToNextHunkHeader",
				["[c"] = "OpenOrScrollUp",
				["]c"] = "OpenOrScrollDown",
				["<c-k>"] = "PeekUp",
				["<c-j>"] = "PeekDown",
			},
		},
	},
}
